//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArticleFormatApp_USST.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArticleFormatApp_USST.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 上理研 的本地化字符串。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap biaoge {
            get {
                object obj = ResourceManager.GetObject("biaoge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap erjibiaoti {
            get {
                object obj = ResourceManager.GetObject("erjibiaoti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 页脚 的本地化字符串。
        /// </summary>
        internal static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 false 的本地化字符串。
        /// </summary>
        internal static string FormulaIncludeChapterNumber {
            get {
                return ResourceManager.GetString("FormulaIncludeChapterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公式 的本地化字符串。
        /// </summary>
        internal static string FormulaLabelName {
            get {
                return ResourceManager.GetString("FormulaLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 wdCaptionPositionBelow 的本地化字符串。
        /// </summary>
        internal static string FormulaLabelPostion {
            get {
                return ResourceManager.GetString("FormulaLabelPostion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 wdSeparatorPeriod 的本地化字符串。
        /// </summary>
        internal static string FormulaSeparator {
            get {
                return ResourceManager.GetString("FormulaSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页眉 的本地化字符串。
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        internal static string Heading {
            get {
                return ResourceManager.GetString("Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 1 的本地化字符串。
        /// </summary>
        internal static string Heading1 {
            get {
                return ResourceManager.GetString("Heading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 2 的本地化字符串。
        /// </summary>
        internal static string Heading2 {
            get {
                return ResourceManager.GetString("Heading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 3 的本地化字符串。
        /// </summary>
        internal static string Heading3 {
            get {
                return ResourceManager.GetString("Heading3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 4 的本地化字符串。
        /// </summary>
        internal static string Heading4 {
            get {
                return ResourceManager.GetString("Heading4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 true 的本地化字符串。
        /// </summary>
        internal static string IncludeChapterNumber {
            get {
                return ResourceManager.GetString("IncludeChapterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap mulu {
            get {
                object obj = ResourceManager.GetObject("mulu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 .Configs.OtherConfig.xml 的本地化字符串。
        /// </summary>
        internal static string OtherConfigPath {
            get {
                return ResourceManager.GetString("OtherConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他标题 的本地化字符串。
        /// </summary>
        internal static string OtherHeading {
            get {
                return ResourceManager.GetString("OtherHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图 的本地化字符串。
        /// </summary>
        internal static string PicLabelName {
            get {
                return ResourceManager.GetString("PicLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 wdCaptionPositionBelow 的本地化字符串。
        /// </summary>
        internal static string PicLabelPostion {
            get {
                return ResourceManager.GetString("PicLabelPostion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 wdSeparatorPeriod 的本地化字符串。
        /// </summary>
        internal static string PicSeparator {
            get {
                return ResourceManager.GetString("PicSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap qitabiaoti {
            get {
                object obj = ResourceManager.GetObject("qitabiaoti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap sanjibiaoti {
            get {
                object obj = ResourceManager.GetObject("sanjibiaoti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap shengcheng {
            get {
                object obj = ResourceManager.GetObject("shengcheng", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap sijibiaoti {
            get {
                object obj = ResourceManager.GetObject("sijibiaoti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 .Configs.Styles.csv 的本地化字符串。
        /// </summary>
        internal static string StylesPath {
            get {
                return ResourceManager.GetString("StylesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 true 的本地化字符串。
        /// </summary>
        internal static string TableExclueLabel {
            get {
                return ResourceManager.GetString("TableExclueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表 的本地化字符串。
        /// </summary>
        internal static string TableLabelName {
            get {
                return ResourceManager.GetString("TableLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 wdCaptionPositionAbove 的本地化字符串。
        /// </summary>
        internal static string TableLabelPostion {
            get {
                return ResourceManager.GetString("TableLabelPostion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 wdSeparatorPeriod 的本地化字符串。
        /// </summary>
        internal static string TableSeparator {
            get {
                return ResourceManager.GetString("TableSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TOC 1 的本地化字符串。
        /// </summary>
        internal static string TOC1 {
            get {
                return ResourceManager.GetString("TOC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TOC 2 的本地化字符串。
        /// </summary>
        internal static string TOC2 {
            get {
                return ResourceManager.GetString("TOC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TOC 3 的本地化字符串。
        /// </summary>
        internal static string TOC3 {
            get {
                return ResourceManager.GetString("TOC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap tupianzhengwen {
            get {
                object obj = ResourceManager.GetObject("tupianzhengwen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap yemeiyejiao {
            get {
                object obj = ResourceManager.GetObject("yemeiyejiao", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap yijibiaoti {
            get {
                object obj = ResourceManager.GetObject("yijibiaoti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap zhaiyao {
            get {
                object obj = ResourceManager.GetObject("zhaiyao", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap zhengwen {
            get {
                object obj = ResourceManager.GetObject("zhengwen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
